var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991},"es6-impl","es3");
$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}},"es6-impl","es3");var gridContainer=null,dots=[];
w3.includeHTML(function(){addButton("Back","../../canvas.html");document.getElementById("title-text").innerText=document.title="Connect Dot";document.getElementById("intro").innerHTML='<i class="material-icons"">touch_app</i>Touch it!';gridContainer=document.getElementById("grid-container");gridContainer.appendChild(canvas);canvas.width=gridContainer.clientWidth;canvas.height=gridContainer.clientHeight;generate();updateEnable()});
function generate(){canvas.width=gridContainer.clientWidth;canvas.height=gridContainer.clientHeight;updateRelativeSize();for(dots=[];50>dots.length;){var a=rand(0,canvas.width),b=rand(0,canvas.height),c=rand(.1,.5,7)*plusOrMinus(),d=rand(.1,.5,7)*plusOrMinus(),e=new ColorHSLA(rand(0,360));dots.push(new Dot(a,b,1,c,d,e))}dots.push(new Dot(Number.MAX_SAFE_INTEGER,Number.MAX_SAFE_INTEGER,3,0,0,new ColorHSLA(0)));render()}
function move(){var a=dots[dots.length-1];for(i in dots)dots[i]!=a&&(dots[i].x+=dots[i].velocityX*relativeSize,dots[i].y+=dots[i].velocityY*relativeSize,0>dots[i].x||dots[i].x>canvas.width||0>dots[i].y||dots[i].y>canvas.height)&&(dots[i].x=rand(0,canvas.width),dots[i].y=rand(0,canvas.height),dots[i].velocityX=rand(.1,.5,7)*(rand(0,1)?1:-1),dots[i].velocityY=rand(.1,.5,7)*(rand(0,1)?1:-1));a.color.h=++a.color.h%361}
function render(){canvas.width=gridContainer.clientWidth;canvas.height=gridContainer.clientHeight;updateRelativeSize(dots);context.clearRect(0,0,canvas.width,canvas.height);for(i in dots){var a=dots.concat();a.splice(i,1);a.sort(function(a,b){return distance(dots[i],a)-distance(dots[i],b)});context.beginPath();for(var b=0;3>b;b++)b<i&&1E3>distance(dots[i],dots[b])&&(context.moveTo(dots[i].x,dots[i].y),context.shadowBlur=1*relativeSize,context.shadowColor=(new ColorHSLA((dots[i].color.h,dots[i].color.h)/
2)).toString(),context.lineWidth=.2*relativeSize,context.strokeStyle="gray",context.lineTo(a[b].x,a[b].y),context.stroke());context.closePath()}for(i in dots)context.beginPath(),context.fillStyle=dots[i].color.toString(),context.shadowBlur=2*relativeSize,context.shadowColor=context.fillStyle,context.arc(dots[i].x,dots[i].y,getRelativeSize(dots[i].size),0,2*Math.PI,!0),context.fill(),context.closePath()}function onUpdate(){move();render()}
document.body.addEventListener("mousemove",function(a){var b=canvas.getBoundingClientRect();dots[dots.length-1].x=a.clientX-b.left;dots[dots.length-1].y=a.clientY-b.top},!1);document.body.addEventListener("touchmove",function(a){var b=canvas.getBoundingClientRect();dots[dots.length-1].x=a.touches[0].clientX-b.left;dots[dots.length-1].y=a.touches[0].clientY-b.top},!1);
document.body.addEventListener("touchend",function(a){dots[dots.length-1].x=Number.MAX_SAFE_INTEGER;dots[dots.length-1].y=Number.MAX_SAFE_INTEGER},!1);
