var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,a){if(a.get||a.set)throw new TypeError("ES3 does not support getters and setters.");b!=Array.prototype&&b!=Object.prototype&&(b[c]=a.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,c,a,d){if(c){a=$jscomp.global;b=b.split(".");for(d=0;d<b.length-1;d++){var e=b[d];e in a||(a[e]={});a=a[e]}b=b[b.length-1];d=a[b];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(a,b,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.fill",function(b){return b?b:function(b,a,d){var c=this.length||0;0>a&&(a=Math.max(0,c+a));if(null==d||d>c)d=c;d=Number(d);0>d&&(d=Math.max(0,c+d));for(a=Number(a||0);a<d;a++)this[a]=b;return this}},"es6-impl","es3");
var gridContainer=null,canvas=document.createElement("canvas");canvas.setAttribute("id","rotate_ball");canvas.setAttribute("class","bordered");var context=canvas.getContext("2d"),handle=null,dots=[],circles=[],lastRelativeSize=1;
w3.includeHTML(function(){addButton("Back","../../canvas.html");gridContainer=document.getElementById("grid-container");document.getElementById("title-text").innerText=document.title="Rotate Ball";document.getElementById("intro").innerHTML="";document.getElementById("grid-container").appendChild(canvas);canvas.width=gridContainer.clientWidth;canvas.height=gridContainer.clientHeight;lastRelativeSize=getRelativeSize(1);generate();toggle()});
function generate(){canvas.width=gridContainer.clientWidth;canvas.height=gridContainer.clientHeight;context.clearRect(0,0,canvas.width,canvas.height);circles=[];for(var b=new Vector2(canvas.width/2,canvas.height/2),c=0;360>c;c+=30){var a=new RotateCircle(0,0,12,Math.PI/2+Math.PI/12*circles.length);a.from(angleToDirection(c*Math.PI/180).multiply(29*lastRelativeSize).add(b));circles.push(a)}circles[0].enable=!0;render()}
function move(){new Vector2(canvas.width/2,canvas.height/2);for(i in circles)circles[i].enable&&(circles[i].angle-=Math.PI/100,circles[i].angle+Math.PI/5<circles[i].startAngle&&(circles[0==i?11:i-1].enable=!0),circles[i].angle+Math.PI<circles[i].startAngle&&(circles[i].angle=circles[i].startAngle,circles[i].enable=!1))}
function render(){canvas.width=gridContainer.clientWidth;canvas.height=gridContainer.clientHeight;var b=getRelativeSize(1);if(lastRelativeSize!=b){var c=b/lastRelativeSize;lastRelativeSize=b;b=new Vector2(c,c);for(i in circles)circles[i].multiply(b);for(i in a)a[i].multiply(b)}context.clearRect(0,0,canvas.width,canvas.height);b=new Vector2(canvas.width/2,canvas.height/2);for(i in circles){context.beginPath();a=Math.abs(circles[i].angle-circles[i].startAngle+Math.PI/2);context.strokeStyle=(new ColorHSLA(vecToAngle(circles[i],
b)+120,100,50,a<Math.PI/2?1-a/Math.PI*1.8:0)).toString();context.shadowBlur=10;context.shadowColor=context.strokeStyle;context.lineWidth=.5*lastRelativeSize;context.arc(circles[i].x,circles[i].y,getRelativeSize(circles[i].radius),0,2*Math.PI,!0);context.stroke();context.closePath();var a=angleToDirection(circles[i].angle+i*Math.PI/12).multiply(getRelativeSize(circles[i].radius)),a=[circles[i].add(a,!0),circles[i].subtract(a,!0)];for(i in a)context.beginPath(),context.fillStyle=(new ColorHSLA(vecToAngle(a[i],
b)+120)).toString(),context.shadowBlur=10,context.shadowColor="gray",context.arc(a[i].x,a[i].y,getRelativeSize(2),0,2*Math.PI,!0),context.fill(),context.closePath()}}function onUpdate(){render();move();handle=requestAnimationFrame(onUpdate)}function toggle(){handle?handle=cancelAnimationFrame(handle):onUpdate()};
